### ISSUE TITLE
[Task](Elektra): hide webconsole for iaas_* domains

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1425]
**Task Description**
The webconsole needs to be hidden for the iaas_* domains.

**Sub-tasks**

- [x] hide webconsole link in main nav bar
- [x] hide webconsole link from navigation
- [x] completely deactivate webconsole if possible (i.e. make it unavailable also if people happen to find the deep link). If it is modeled as a service we could mark it as unavailable for these domains. Or maybe the policy can be adjusted so people aren't allowed to access the action at all
