### ISSUE TITLE
[Task](elektra): landingpage upgrade juno-ui-components and adjust Pageheader with SAP logo

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1432]
**Task Description**
Between the version of juno-ui-components that is currently in use in Elektra and the latest version of juno-ui-components there has been a change that is breaking for the landing page app. The change is that by default we do not render the SAP logo but the Juno logo. In order to have the SAP logo for the Elektra landing page it needs to be imported separately and passed to the Pageheader as a prop (see [PageHeader storybook documentation](https://cloudoperators.github.io/juno/?path=/docs/layout-pageheader--docs)).

**Sub-tasks**

- [x] Update juno-ui-components to latest version
- [x] add SAP logo svg to landingpage app
- [x] pass SAP logo as a component as prop `logo` to PageHeader
- [x] verify that juno-ui-components upgrade doesn't break anything in Keymanager app
