### ISSUE TITLE
[Task](ci/elektra): setup workflows for checks

### ISSUE THREAD

**Issue by andypf** [sapcc/elektra#1443]
## Description
Use `cloudoperators/juno` repo as a template to create workflows for checks

## **Sub-tasks**

- [ ] **Create a workflow for PR title validation**
  - File: `ci-title-lint-check.yaml`

- **Set up formatting workflows**
  - [ ] **Prettier**: Apply to non-Ruby files.
  - [ ] **Rubocop**: Apply to Ruby files (includes both formatting and linting).

- [ ] **Add JavaScript linting**

- [x] **Integrate [Husky](https://typicode.github.io/husky/)** for pre-commit hooks and additional checks
