### ISSUE TITLE
[Task](elektra): More Bedrock changes

### ISSUE THREAD

**Issue by edda** [sapcc/elektra#1449]
**Task Description**
One additional change related to the iaas domains came to light. Additonally there seems to be a regression in the "Edit project" view, possibly due to the removal of the Masterdata plugin for these domains. And we seem to have forgotten to remove the placeholder hint related to allowed cidr ranges for iaas domains.

**Sub-tasks**

- [x] (Bug): "Edit Project" view doesn't render properly for `iaas` domains
- [x] (Bug): when creating a new private network cidr range shouldn't be validated for iaas domains. Also the placeholder hint `must be in cidr range like 10.180.0.0/16` must be removed
- [x] We need to change the logic that loads the "useful links" help texts for `iaas` domains such that they load not the file containing the internal links but one that contains external docu links. The files follow a specific naming schema, so I propose to extend the schema to be able differentiate between the usecases. The helper which loads the correct links is `load_help_text` in the dashboard controller (https://github.com/sapcc/elektra/blob/master/app/controllers/dashboard_controller.rb#L300)
