### ISSUE TITLE
[Task](elektra): integrate 3rd-party UIs via npm

### ISSUE THREAD

**Issue by andypf** [sapcc/elektra#1458]
## Task Description

As part of the decommissioning of the assets server, we need to integrate third-party UIs in elektra, such as **Limes** and **Email**, without relying on the assets server. The proposed approach is to use the **GitHub npm registry**. Instead of loading these UIs at runtime from the assets server, they can be added to `package.json` in **Elektra** and included at build time.

We'll begin with **Limes** and then extend this approach to include **Email**.

### Subtasks

- [x] Create a GitHub workflow in the Limes UI repository to publish an npm package to the GitHub npm registry.
- [x] Add the published npm package to Elektra.
- [x] Integrate and ensure functionality within Elektra.
- [ ] Extend this process to include the Email UI.
